# spring.application.name=nguyenquoctrung
# Database connection properties
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/cakestore?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.jakarta.persistence.validation.mode=none

# Spring Security
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


# Đọc file .env nếu có (Spring Boot 2.4+ hỗ trợ cấu trúc này)
spring.config.import=optional:file:.env[.properties], optional:file:../.env[.properties], optional:file:./doanmon/.env[.properties]

#Nhập thông tin Client Id và Client Secret từ Google Cloud Console
spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET:}
server.forward-headers-strategy=framework

server.error.path=/error

# File Upload Settings
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
# VNPay settings (test environment)
vnp.tmnCode=${VNP_TMNCODE:EC93RPTT}
vnp.hashSecret=${VNP_HASHSECRET:V3UPNFSP4Y9SDQZJNK34SHFP7DHFG903}
vnp.url=${VNP_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
vnp.returnUrl=${VNP_RETURN_URL:http://localhost/checkout/result}
#vnp.returnUrl=http://localhost:8080/checkout/result
